'use strict';

const CONTENT_OFFSET = 0x10;

module.exports = exports = {
    CHESTS: 0x5dcd + CONTENT_OFFSET,
    CHEST_CONTENTS: [
        'NONE',
        'ERDRICKS_ARMOR',
        'HERB',
        'MAGIC_KEY',
        'TORCH',
        'FAIRY_WATER',
        'WINGS',
        'DRAGON_SCALE',
        'FAIRY_FLUTE',
        'FIGHTERS_RING',
        'ERDRICKS_TOKEN',
        'GWAELINS_LOVE',
        'CURSED_BELT',
        'SILVER_HARP',
        'DEATH_NECKLACE',
        'STONES_OF_SUNLIGHT',
        'STAFF_OF_RAIN',
        'ERDRICKS_SWORD',
        'GOLD'
    ],
    ENEMIES: 0x5e4b + CONTENT_OFFSET,
    ENEMY_LIST: [
        'SLIME',
        'RED_SLIME',
        'DRAKEE',
        'GHOST',
        'MAGICIAN',
        'MAGIDRAKEE',
        'SCORPION',
        'DRUIN',
        'POLTERGEIST',
        'DROLL',
        'DRAKEEMA',
        'SKELETON',
        'WARLOCK',
        'METAL_SCORPION',
        'WOLF',
        'WRAITH',
        'METAL_SLIME',
        'SPECTER',
        'WOLFLORD',
        'DRUINLORD',
        'DROLLMAGI',
        'WYVERN',
        'ROGUE_SCORPION',
        'WRAITH_KNIGHT',
        'GOLEM',
        'GOLDMAN',
        'KNIGHT',
        'MAGIWYVERN',
        'DEMON_KNIGHT',
        'WEREWOLF',
        'GREEN_DRAGON',
        'STARWYVERN',
        'WIZARD',
        'AXE_KNIGHT',
        'BLUE_DRAGON',
        'STONEMAN',
        'ARMORED_KNIGHT',
        'RED_DRAGON',
        'DRAGONLORD_1',
        'DRAGONLORD_2'
    ],
    MAPS: [
        'NO_MAP',
        'OVERWORLD',
        'CHARLOCK',
        'HAUKSNESS',
        'TANTEGEL',
        'TANTEGEL_THRONE_ROOM',
        'CHARLOCK_THRONE_ROOM',
        'KOL',
        'BRECCONARY',
        'GARINHAM',
        'CANTLIN',
        'RIMULDAR',
        'TANTEGEL_BASEMENT',
        'NORTHERN_SHRINE',
        'SOUTHERN_SHRINE',
        'CHARLOCK_CAVE_1',
        'CHARLOCK_CAVE_2',
        'CHARLOCK_CAVE_3',
        'CHARLOCK_CAVE_4',
        'CHARLOCK_CAVE_5',
        'CHARLOCK_CAVE_6',
        'SWAMP_CAVE',
        'MOUNTAIN_CAVE',
        'MOUNTAIN_CAVE_2',
        'GARINS_GRAVE_1',
        'GARINS_GRAVE_2',
        'GARINS_GRAVE_3',
        'GARINS_GRAVE_4',
        'ERDRICKS_CAVE',
        'ERDRICKS_CAVE_2'
    ],
    SEARCH_ITEMS: 0x1e136 + CONTENT_OFFSET,
    SPELLS: [
        'HEAL',
        'HURT',
        'SLEEP',
        'RADIANT',
        'STOPSPELL',
        'OUTSIDE',
        'RETURN',
        'REPEL',
        'HEALMORE',
        'HURTMORE'
    ],
    STATS: 0x60cd + CONTENT_OFFSET,
    WARPS: [
        'GARINHAM',
        'STAFF_SHRINE',
        'KOL',
        'BRECCONARY',
        'TANTEGEL',
        'SWAMP_NORTH',
        'CHARLOCK',
        'SWAMP_SOUTH',
        'MOUNTAIN_CAVE',
        'RIMULDAR',
        'HAUKSNESS',
        'CANTLIN',
        'JERK_CAVE',
        'ERDRICKS_CAVE',
        'CHARLOCK_SURFACE_1',
        'CHARLOCK_SURFACE_2',
        'CHARLOCK_SURFACE_3',
        'TANTEGEL_BASEMENT',
        'BLANK',
        'GARINS_GRAVE'
    ],
    WARPS_FROM: 0x1f3c8 + CONTENT_OFFSET,
    WARPS_TO: 0x1f461 + CONTENT_OFFSET
};
